### ISSUE TITLE
Submit!

### ISSUE THREAD

**Issue by dfm** [dfm/k2-paper#24]
OK folks. I think we could still submit today as soon as
- [x] @timothydmorton signs off on the astro FP section. It still has some to dos but I think that they're redundant
- [x] -I put in an example of how to use the posterior samples.-
- [x] @davidwhogg and @benmontet comment on #11 and sign off

Let me know if y'all think that there's anything else!

**Comment by benmontet** [comment]
I just commented on #11, I will read through right now and sign off after.

**Comment by timothydmorton** [comment]
I'm having students in and out of my office throughout the day, so my contributions have been sporadic.  my next meeting isn't until 2pm, so i have a bit of uninterrupted stretch right now.  I will have more changes to the FPP text as well as some rough a priori-expected FPP numbers to drop in.

**Comment by dfm** [comment]
Great. Let me know if there's anything I can do to help!

**Comment by benmontet** [comment]
A few thoughts:

1) I think it is worth saying somewhere this technique is broadly applicable to any astrophysical phenomenon that might be observed in K2 data, it's not exclusive to transits. One could model ellipsoidal variations simultaneously, or stellar rotation or whatever. It's obvious, but should still be said somewhere for people who need obvious things stated. I'm not sure where, which is why I'm not doing it myself.

2) You are almost certainly aware that the astro FP paragraph with the todos is almost entirely redundant over the previous two paragraphs. I don't think anything would be lost by just deleting that paragraph entirely. I would be remiss if I didn't say anything in the 0.02% change you hadn't noticed.

3) We should probably thank the Kepler/K2 teams in the acknowledgements.

Once these have all been addressed, I sign off on this version.

**Comment by dfm** [comment]
I'll do number 1. Tim is working on 2. Can you draft something for 3, @benmontet?

**Comment by timothydmorton** [comment]
OK, FPP text in.  y'all should take a look.  I'm reading through the rest now; will post any questions I have.

**Comment by benmontet** [comment]
(3) is in. I'll check out the FPP text now.

**Comment by benmontet** [comment]
I like the FPP discussion. I think a figure is warranted. Maybe the one from the diagnostic plots for one of the false positives, showing the measured offset compared to the random realizations? 

Let's mention the bootstrap results for these false positives too---what's the probability these offsets are due to chance? What was the significance at which we declared a False Positive?

**Comment by benmontet** [comment]
Also, I never realized how truly terrible TRILEGAL is as an acronym. "modeL of thE"?!?!

**Comment by timothydmorton** [comment]
I agree with @benmontet ; some more quantitative info on the centroid tests (e.g., what level offset did you measure) would be good, with maybe a figure to boot.  Do either of the flagged centroid-motion systems have obvious contamination from other stars?

aside from this, I read it through and have no complaints/major questions.

**Comment by dfm** [comment]
OK great. I'm on this. Can one of you try to add something to the discussion about the broader applicability of this method while I generate these figures? Thanks!

**Comment by benmontet** [comment]
Paragraph added in the discussion.

**Comment by dfm** [comment]
I've added a figure and some discussion for the centroid offsets. I did it just by eye originally but in both cases, the inconsistency is ~3-sigma and there is maybe some evidence of contamination but I'm not sure...

**Comment by dfm** [comment]
My housemate suggests TIMESEX (TrIdiMEnSional model of thE galaXy) as a better acronym for TRILEGAL.

**Comment by dfm** [comment]
I'm going to skip putting a demo of how to use the samples into the paper. Instead I'm going to put it (with sample code) into the README for the data release.

**Comment by dfm** [comment]
I think we're done! I'm going to give it one last read through and then get ready to post at 4!

**Comment by timothydmorton** [comment]
I think that figure gives a decent enough quantitative sense of the method.  And I don't know if it's just my pdf viewer or not, but it looks like half the zero is cut off on the x-axis tick labels in the new figure.

**Comment by dfm** [comment]
whoa. You're right. I'll fix that!

**Comment by benmontet** [comment]
I'm satisfied. There's nothing else specific to do, right? I'll read through once more too and put a beer in the fridge.

**Comment by dfm** [comment]
I fixed the figure! Good catch. 

Thanks y'all! This GitHub collaboration thing was **fun**!

**Comment by davidwhogg** [comment]
I SIGN OFF

**Comment by benmontet** [comment]
I presume we will submit at 4:00:01 and are now just waiting?

**Comment by dfm** [comment]
Yup. It's processing fine on ArXiv. We're ready to go.

**Comment by davidwhogg** [comment]
Damn I owe you some beer...!

**Comment by davidwhogg** [comment]
have you submitted to the _Journal_ already?  If so, I presume you say so in the "Comments" field?  Otherwise "to be submitted to..."?

**Comment by benmontet** [comment]
Hey, here's a question no one ever asked: where are we submitting to?

**Comment by dfm** [comment]
ApJ

**Comment by dfm** [comment]
I assert.

**Comment by benmontet** [comment]
Acceptable.

**Comment by dfm** [comment]
one can only hope...

:clock4:

**Comment by benmontet** [comment]
Great success!?

**Comment by dfm** [comment]
Posted to ArXiv. I had internet issues so I ended up with "Mon, 16 Feb 2015 16:00:39 EST" but hopefully we're still top 10....

**Comment by benmontet** [comment]
Celebratory beer time.

(It will make the paper grading go down easier too).

**Comment by timothydmorton** [comment]
congrats!
